source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'Toki_Tests' do
  pod 'Toki', :path => '../'
  pod 'Mockingjay', git: 'https://github.com/shams-ahmed/Mockingjay.git', branch: 'bug/podspec-swift'

  pod 'Quick'
  pod 'Nimble'
end
